# For this particular Model we will be using Shakespeare's works

# Loading the data

In [1]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
#reading in the data
text=open("shakespeare.txt",'r').read()

In [3]:
#Glancing at the data
text[:500]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [4]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [5]:
#getting the distinct characters
vocab=sorted(set(text))

In [6]:
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [7]:
len(vocab)

84

# Encoding the data

In [8]:
for pair in enumerate(vocab):
  print (pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


We want to have a dictionary from which we can access the character and in tun itll give us the index

In [9]:
char_to_ind={char:ind for ind,char in enumerate(vocab)}

In [10]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

Next, we want an array through which we can access a character given the index

In [11]:
ind_to_char=np.array(vocab)

In [12]:
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '|', '}'], dtype='<U1')

In [13]:
ind_to_char[33]

'H'

In [14]:
#and to view the chracter's index
char_to_ind['X']

49

Creating the encoding: essentially turning all the text in our document into integer values

In [15]:
encoded_text=np.array([char_to_ind[c] for c in text])

In [16]:
encoded_text.shape

(5445609,)

In [17]:
text[:500]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [18]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

# Creating the dataset
1. Defining length of sequences
2. Generating a character dataset from the encoded text with the help of tf Dataset
3. Generate sequences from the character dataset
4. Create a comprehensive dataset from these sequences by generating input sequences and target sequences

In [19]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [20]:
line="From fairest creatures we desire increase,"

In [21]:
#length of a typical line:
len(line)

42

In [22]:
lines='''
From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  '''

In [23]:
#typical length of a sequence
len(lines)

135

**character_dataset will allow us to use the batch method , which will help  in creating batches for the dataset**

In [24]:
char_dataset=tf.data.Dataset.from_tensor_slices(encoded_text)

In [25]:
type(char_dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [26]:
for i in char_dataset.take(500):
  print(i)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(12, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(31, shape=(), dtype=int64)
tf.Tensor(73, shape=(), dt

**To view the elements in a simple manner cast them as numpy array**

In [27]:
for i in char_dataset.take(500):
  print(np.array(i))

0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
12
0
1
1
31
73
70
68
1
61
56
64
73
60
74
75
1
58
73
60
56
75
76
73
60
74
1
78
60
1
59
60
74
64
73
60
1
64
69
58
73
60
56
74
60
8
0
1
1
45
63
56
75
1
75
63
60
73
60
57
80
1
57
60
56
76
75
80
5
74
1
73
70
74
60
1
68
64
62
63
75
1
69
60
77
60
73
1
59
64
60
8
0
1
1
27
76
75
1
56
74
1
75
63
60
1
73
64
71
60
73
1
74
63
70
76
67
59
1
57
80
1
75
64
68
60
1
59
60
58
60
56
74
60
8
0
1
1
33
64
74
1
75
60
69
59
60
73
1
63
60
64
73
1
68
64
62
63
75
1
57
60
56
73
1
63
64
74
1
68
60
68
70
73
80
21
0
1
1
27
76
75
1
75
63
70
76
1
58
70
69
75
73
56
58
75
60
59
1
75
70
1
75
63
64
69
60
1
70
78
69
1
57
73
64
62
63
75
1
60
80
60
74
8
0
1
1
31
60
60
59
5
74
75
1
75
63
80
1
67
64
62
63
75
5
74
1
61
67
56
68
60
1
78
64
75
63
1
74
60
67
61
9
74
76
57
74
75
56
69
75
64
56
67
1
61
76
60
67
8
0
1
1
38
56
66
64
69
62
1
56
1
61
56
68
64
69
60
1
78
63
60
73
60
1
56
57
76
69
59
56
69
58
60
1
67
64
60
74
8
0
1
1
45
63
80
1
74
60
67
61
1
75
63
80
1
61
70
60
8
1
75
70
1
75
63


**To view these as characters we can use ind_to_char**

In [28]:
for i in char_dataset.take(500):
  print(ind_to_char[np.array(i)])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


**Now well make sequences from the char_dataset**

In [29]:
#Defingin seq_length
seq_len=120

In [30]:
sequences=char_dataset.batch(seq_len+1,drop_remainder=True)
#we define the batch size = sequence length +1 because of 0 indexing

In [31]:
for i in sequences.take(500):
  print(np.array(i))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75
  1]
[56 74  1 75 63 60  1 73 64 71 60 73  1 74 63 70 76 67 59  1 57 80  1 75
 64 68 60  1 59 60 58 60 56 74 60  8  0  1  1 33 64 74  1 75 60 69 59 60
 73  1 63 60 64 73  1 68 64 62 63 75  1 57 60 56 73  1 63 64 74  1 68 60
 68 70 73 80 21  0  1  1 27 76 75  1 75 63 70 76  1 58 70 69 75 73 56 58
 75 60 59  1 75 70  1 75 63 64 69 60  1 70 78 69  1 57 73 64 62 63 75  1
 60]
[80 60 74  8  0  1  1 31 60 60 59  5 74 75  1 75 63 80  1 67 64 62 63 75
  5 74  1 61 67 56 68 60  1 78 64 75 63  1 74 60 67 61  9 74 76 57 74 75
 56 69 75 64 56 67  1 61 76 60 67  8  0  1  1 38 56 66 64 69 62  1 56  1
 61 56 68 64 69 60  1 78 63 60 73 60  1 5

In [32]:
def create_seq_targets(seq):
  input_txt=seq[:-1]
  target_txt=seq[1:]
  return input_txt,target_txt

In [33]:
dataset=sequences.map(create_seq_targets)

In [34]:
for input_txt,target_txt in dataset.take(1):
  print(np.array(input_txt))
  print("".join(ind_to_char[np.array(input_txt)]))
  print(np.array(target_txt))
  
  print("".join(ind_to_char[np.array(target_txt)]))
  

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But
[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [35]:
batch_size=128

In [36]:
buffer_size=10000
dataset=dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True)

In [37]:
dataset

<BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

# The above dataset has the input_txt,target_txt of the shape (128,120)

# Creating the model
1. Defining he loss function
2. defining the vocab_size
3. defining the model
4. importing layers GRU,Embeding
5. define rnn_neurons
6. DEFINE EMBED_DIMS


In [48]:
vocab_size=84

In [47]:
embed_dims=64

In [42]:
rnn_neurons=1026

In [39]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [45]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    Args:
      y_true: Ground truth values.
      y_pred: The predicted values.
      from_logits: Whether `y_pred` is expected to be a logits tensor. By default,
        we assume that `y_pred` encodes a probability distribution.
      axis: Defaults to -1. The dimension along which the entropy is
        computed.
    
    Returns:
      Sparse categorical crossentropy loss value.



In [46]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True, axis=-1)

In [43]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,GRU,Embedding

In [83]:
def create_model(vocab_size,rnn_neurons,embed_dims,batch_size):
  model=Sequential()
  model.add(Embedding(vocab_size,embed_dims,batch_input_shape=[batch_size,None]))
  model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
  model.add(Dense(vocab_size))
  model.compile(loss=sparse_cat_loss,optimizer='adam')
  return model

In [84]:
model=create_model(vocab_size=vocab_size,rnn_neurons=rnn_neurons,embed_dims=embed_dims,batch_size=batch_size)

In [85]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (128, None, 64)           5376      
                                                                 
 gru_1 (GRU)                 (128, None, 1026)         3361176   
                                                                 
 dense_1 (Dense)             (128, None, 84)           86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


# Making a prediction on a sample

In [58]:
for input_example_batch,target_example_batch in dataset.take(1):
  example_batch_predictions=model(input_example_batch)

In [59]:
example_batch_predictions.shape

TensorShape([128, 120, 84])

1. 128-batch_size
2. 120-sequence_size
3. 84-vocab_size

In [62]:
example_batch_predictions

<tf.Tensor: shape=(128, 120, 84), dtype=float32, numpy=
array([[[ 1.63632922e-03, -5.31259342e-04,  3.34047247e-03, ...,
          3.28196958e-03,  7.32711935e-03,  2.46589631e-03],
        [ 2.56020180e-03,  5.90892648e-03, -6.00427855e-03, ...,
         -2.68618250e-03,  2.82784947e-03,  4.78662783e-03],
        [ 1.02829665e-03,  4.89813322e-03, -3.86426225e-03, ...,
         -1.20398623e-03,  7.31870485e-03,  6.34783087e-03],
        ...,
        [-2.53379508e-03, -7.21152592e-03, -8.35707528e-04, ...,
         -3.78535688e-03, -2.24129995e-04, -5.95939998e-03],
        [ 3.62287974e-05,  3.77239939e-03, -9.57680866e-03, ...,
         -4.50282358e-03, -1.26009679e-03,  8.89844378e-05],
        [-5.37630683e-03, -1.24760612e-03, -2.52498081e-03, ...,
          7.82599207e-03,  3.33484984e-03, -9.21095908e-03]],

       [[-9.60834557e-04,  1.95875624e-03,  1.33226882e-03, ...,
         -9.73325502e-03,  2.93150917e-03, -4.32069367e-03],
        [ 1.81796867e-03, -1.45226411e-04, -3.2

The above are probabilities of characters

In [63]:
example_batch_predictions[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[ 1.6363292e-03, -5.3125934e-04,  3.3404725e-03, ...,
         3.2819696e-03,  7.3271194e-03,  2.4658963e-03],
       [ 2.5602018e-03,  5.9089265e-03, -6.0042785e-03, ...,
        -2.6861825e-03,  2.8278495e-03,  4.7866278e-03],
       [ 1.0282967e-03,  4.8981332e-03, -3.8642623e-03, ...,
        -1.2039862e-03,  7.3187049e-03,  6.3478309e-03],
       ...,
       [-2.5337951e-03, -7.2115259e-03, -8.3570753e-04, ...,
        -3.7853569e-03, -2.2413000e-04, -5.9594000e-03],
       [ 3.6228797e-05,  3.7723994e-03, -9.5768087e-03, ...,
        -4.5028236e-03, -1.2600968e-03,  8.8984438e-05],
       [-5.3763068e-03, -1.2476061e-03, -2.5249808e-03, ...,
         7.8259921e-03,  3.3348498e-03, -9.2109591e-03]], dtype=float32)>

tf.random.categorical takes in logits (example_batch__predictions) and num of smaples

In [71]:
sampled_indices=tf.random.categorical(example_batch_predictions[0],num_samples=1)

In [72]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[11],
       [26],
       [59],
       [27],
       [65],
       [66],
       [72],
       [22],
       [61],
       [67],
       [ 9],
       [ 4],
       [76],
       [26],
       [22],
       [28],
       [80],
       [ 3],
       [39],
       [37],
       [51],
       [43],
       [18],
       [10],
       [17],
       [ 2],
       [82],
       [68],
       [44],
       [34],
       [74],
       [34],
       [ 3],
       [81],
       [13],
       [81],
       [28],
       [64],
       [32],
       [ 9],
       [35],
       [65],
       [25],
       [40],
       [39],
       [73],
       [64],
       [58],
       [59],
       [48],
       [40],
       [13],
       [67],
       [65],
       [71],
       [67],
       [ 5],
       [ 1],
       [51],
       [66],
       [57],
       [52],
       [19],
       [29],
       [ 3],
       [56],
       [ 2],
       [20],
       [77],
       [73],
       [25],
       [28],
       [55],
   

In [73]:
sampled_indices=tf.squeeze(sampled_indices,axis=-1).numpy()

In [74]:
sampled_indices

array([11, 26, 59, 27, 65, 66, 72, 22, 61, 67,  9,  4, 76, 26, 22, 28, 80,
        3, 39, 37, 51, 43, 18, 10, 17,  2, 82, 68, 44, 34, 74, 34,  3, 81,
       13, 81, 28, 64, 32,  9, 35, 65, 25, 40, 39, 73, 64, 58, 59, 48, 40,
       13, 67, 65, 71, 67,  5,  1, 51, 66, 57, 52, 19, 29,  3, 56,  2, 20,
       77, 73, 25, 28, 55, 55, 22, 28,  6, 43,  1, 39, 23, 50, 79, 45, 46,
       79, 80, 25, 80, 21, 13, 41, 49,  7, 73, 71, 31, 61, 68, 43, 76, 32,
        3, 24, 43, 76, 68,  6, 66, 14, 45, 54,  9,  8,  4, 61, 43, 49, 11,
       39])

In [75]:
ind_to_char[sampled_indices]

array(['0', 'A', 'd', 'B', 'j', 'k', 'q', ';', 'f', 'l', '-', '&', 'u',
       'A', ';', 'C', 'y', '"', 'N', 'L', 'Z', 'R', '7', '.', '6', '!',
       '|', 'm', 'S', 'I', 's', 'I', '"', 'z', '2', 'z', 'C', 'i', 'G',
       '-', 'J', 'j', '?', 'O', 'N', 'r', 'i', 'c', 'd', 'W', 'O', '2',
       'l', 'j', 'p', 'l', "'", ' ', 'Z', 'k', 'b', '[', '8', 'D', '"',
       'a', '!', '9', 'v', 'r', '?', 'C', '`', '`', ';', 'C', '(', 'R',
       ' ', 'N', '<', 'Y', 'x', 'T', 'U', 'x', 'y', '?', 'y', ':', '2',
       'P', 'X', ')', 'r', 'p', 'F', 'f', 'm', 'R', 'u', 'G', '"', '>',
       'R', 'u', 'm', '(', 'k', '3', 'T', '_', '-', ',', '&', 'f', 'R',
       'X', '0', 'N'], dtype='<U1')

In [76]:
epochs=30

In [77]:
model.fit(dataset,epochs=epochs)

Epoch 1/30
 65/351 [====>.........................] - ETA: 38:36 - loss: 3.5956

KeyboardInterrupt: ignored

In [80]:
from tensorflow.keras.models import load_model

In [86]:
model=create_model(vocab_size=vocab_size,rnn_neurons=rnn_neurons,embed_dims=embed_dims,batch_size=1)
model.load_weights('shakespeare_gen.h5')
model.build(tf.TensorShape([1,None]))

In [87]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (1, None, 64)             5376      
                                                                 
 gru_2 (GRU)                 (1, None, 1026)           3361176   
                                                                 
 dense_2 (Dense)             (1, None, 84)             86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


# Now we can make a function that can generate text

gen_size: How many characters to generate<br>
temp: can be played around with, its used for adjusting the randomness<br>
start_seed:would just be a raw string, that the user can pass in
<br><br>
a. convert start seed--> get index<br>
b. expand its dimensions<br>
c. reset states<br>
d. make a loop to run for gen_size<br>
e. pass the input evaluation to the model to get a prediction<br>
f. undo the exapanded dimensions by squeezing to grab the predictions<br>
g. get a predicted id with the help of tf.random.categorical (this draws from the categorical distribution) and convert to numpy to get a single digit<br>
h. expand it back out so we can get the input_eval shifted forward , by our predicted text

In [88]:
def generate_text(model,start_seed,gen_size=500,temp=1.0):
  num_generate=gen_size
  input_eval=[char_to_ind[c] for c in start_seed]
  #we want to expand this to match the input shape
  input_eval=tf.expand_dims(input_eval,0)
  text_generated=[] 
  #this is going to hold our generated text

  temperature=temp

  model.reset_states()

  for i in range(num_generate):
    #we'll first generate some predictions
    predictions=model(input_eval) # passing converted input text indexes to the model
    predictions=tf.squeeze(predictions,0)

    #we want to use categorical distribution to select the next character

    predictions=predictions/temperature

    predicted_id=tf.random.categorical(predictions,num_samples=1)[-1,0].numpy()

    input_eval=tf.expand_dims([predicted_id],0)

    text_generated.append(ind_to_char[predicted_id])
  return (start_seed+"".join(text_generated))

In [89]:
print(generate_text(model,"JULIET",1000))

JULIETTES. Visit Malvolio is come.
  POET. Sir, hath some pinches hour thy looks;
    At letters--where I upon her lord,
    It were acted without this did grace,
    To live a breaking fight as heavy slander,
    And they began, and therein were the night
    Which else o'erraught made presentine.
  IAGO. At services mine incasion that I have haw;
    If this persuadesm of our cruel tears,
    Or say 'em, look, there is a time unto?
  ALL. We'll observing stuffs our love.        [Exit Back.]
    Please you, my lord?
  KING RICHARD. What is I have priveded your counar?  
  LUCIUS. His princess.
  NORTHUMBERLAND. Heartily confound a thousand times  
    From first with one another did not cast.
  EXETER. Farewell, and ever. Never to be indeed,
    'Tis I am advis'd turnivated,
    The watery minister of man might
    Can no kiss in? Wasthered, when the first best blood
    Matches counsel, lords, to view that make
    too cold boy, and rehave leer, and she swears our faces
    That long